### ISSUE TITLE
Support numpy arrays

### ISSUE THREAD

**Issue by alexandrnikitin** [sepandhaghighi/pycm#10]
They are basically used everywhere, no need to convert. They are faster and memory efficient. It's an issue with large lists. The library supports only lists at the moment https://github.com/sepandhaghighi/pycm/blob/c04dd6c5bb884b024311fb76f0c157035130cf98/pycm/pycm_obj.py#L13

**Comment by sepandhaghighi** [comment]
@alexandrnikitin Thanks for your point.
I will add this in next version ;-)

**Comment by sepandhaghighi** [comment]
fixed

**Comment by alexandrnikitin** [comment]
Awesome! Thank you!
