### ISSUE TITLE
Add the capability of comparing two CMs

### ISSUE THREAD

**Issue by alirezazolanvari** [sepandhaghighi/pycm#111]
Add the capability of comparing two CMs by appropriate parameters.

**Comment by sepandhaghighi** [comment]
@alirezazolanvari 

Now first version of `Compare` class is ready.
1. First please read `Compare` validation flow and complete `COMPARE_FORMAT_ERROR` , `COMAPRE_TYPE_ERROR` , `COMPARE_DOMAIN_ERROR` & `COMPARE_NUMBER_ERROR` in `pycm_param.py`.
2. Please test `Compare` method and give me some feedback ;-)
3. `Compare` or `compare` ?
4. Which methods are necessary ? (+ `scores` and `best`)

**Comment by sepandhaghighi** [comment]
Thanks for your effort ;-)


Please check lower/upper case style.




Get Outlook for Android







On Tue, Mar 12, 2019 at 12:23 PM +0330, "Alireza Zolanvari" <notifications@github.com> wrote:












@sepandhaghighi

Please check the error messages.

**Comment by alirezazolanvari** [comment]
> @alirezazolanvari
> 
> Now first version of `Compare` class is ready.
> 
> 1. First please read `Compare` validation flow and complete `COMPARE_FORMAT_ERROR` , `COMAPRE_TYPE_ERROR` , `COMPARE_DOMAIN_ERROR` & `COMPARE_NUMBER_ERROR` in `pycm_param.py`.
> 2. Please test `Compare` method and give me some feedback ;-)
> 3. `Compare` or `compare` ?
> 4. Which methods are necessary ? (+ `scores` and `best`)

- About the third question I prefer "Compare" like all other classes in this module

**Comment by alirezazolanvari** [comment]
I think everything seems O.K.

**Comment by sepandhaghighi** [comment]
@alirezazolanvari 
1. Class-base compare (`by_class` and `weight`) added to `Compare` class.
Please test and give me some feedback ;-)
2. Please complete `COMPARE_WEIGHT_ERROR` in `pycm_param.py`

**Comment by sepandhaghighi** [comment]
@alirezazolanvari 

`Compare` class added to `Document.ipynb`, please take a look.
For next step we need an example (for `Example8.ipynb` and `Document.ipynb`) after that I will update `README.md` and `Document.ipynb`.
