### ISSUE TITLE
Parameter recommender

### ISSUE THREAD

**Issue by AlirezaZolanvari** [sepandhaghighi/pycm#112]
recommend most related parameters considering if the dataset is unbalanced or not, or the classification is binary or not

**Comment by sepandhaghighi** [comment]
@AlirezaZolanvari 
Please list here parameters for each items : 

1. Balanced
2. Unbalanced
3. Multi-class
4. Binary

* And also thresholds for unbalance detection.

**Comment by sepandhaghighi** [comment]
@AlirezaZolanvari 

Good approach, but what is our threshold for this division ? please implement your function in `pycm_util.py` as `unbalance_check(classes,POP)` (`POP` is a dictionary for all classes population and `classes` is a list),
This function should return a `bool` value.

**Comment by AlirezaZolanvari** [comment]
@sepandhaghighi 

Is not a list of classes population sufficient for the Input of this function?

**Comment by sepandhaghighi** [comment]
> @sepandhaghighi
> 
> Is not a list of classes population sufficient for the Input of this function?

@AlirezaZolanvari 
In most of functions I passed `classes` as a separated list to decrease key extraction and sort elapsed time in large data set. But  in this function you are right we only need `max` and `min` of population.
`POP` dictionary is sufficient.

**Comment by AlirezaZolanvari** [comment]
@sepandhaghighi 
For our first test 3 was chosen as the unbalance_ratio threshold

**Comment by sepandhaghighi** [comment]
> @sepandhaghighi
> For our first test 3 was chosen as the unbalance_ratio threshold

@AlirezaZolanvari Thanks for your efforts ;-)
- I think it will be better if rename this function to `imbalance_check`
- Please save constants like `balance_ratio` in `pycm_param.py`  (Note : uppercase)

**Comment by sepandhaghighi** [comment]
@AlirezaZolanvari 

In next part we need another function like `statistic_recommend` (or something like this)

Input : 
1. `classes` as list  (for binary detection)
2. `is_imbalanced` as bool

Output : 

List of most related parameters names for this type of dataset, parameters names should save separately as lists in `pycm_param.py` for example : 

`BINARY_RECOMMEND = ["ACC","MCC",""PLR"]`
`MULTICLASS_RECOMMEND = ["Kappa","MCC",""NLR"]`

Note : names from `PARAMS_LINK` in `pycm_param.py`

**Comment by AlirezaZolanvari** [comment]
@sepandhaghighi 
Please declare the recommended parameters for each of the cases in `pycm_param.py`

**Comment by sepandhaghighi** [comment]
@AlirezaZolanvari 
Nice work, thanks for your efforts

I updated `BINARY_RECOMMEND`,`MULTICLASS_RECOMMEND` ,`IMBALANCED_RECOMMEND` and also removed `BALANCED_RECOMMEND`.

Please take a look at these lists and update them ;-)

**Comment by AlirezaZolanvari** [comment]
> @AlirezaZolanvari
> Nice work, thanks for your efforts
> 
> I updated `BINARY_RECOMMEND`,`MULTICLASS_RECOMMEND` ,`IMBALANCED_RECOMMEND` and also removed `BALANCED_RECOMMEND`.
> 
> Please take a look at these lists and update them

The recommendation lists is checked and looks fine. Let me get back to you later. ;)

**Comment by sepandhaghighi** [comment]
@AlirezaZolanvari 

I updated `ConfusionMatrix` object and `save_html` method with recommendation system and also added dataset-type section to HTML report.
Please take a look at these updates and fix any possible bug that was not found by me.

Our last missions in this issue : 
- Finalize recommendations lists
- Update documents for recommendation system

**Comment by AlirezaZolanvari** [comment]
> @AlirezaZolanvari
> 
> I updated `ConfusionMatrix` object and `save_html` method with recommendation system and also added dataset-type section to HTML report.
> Please take a look at these updates and fix any possible bug that was not found by me.
> 
> Our last missions in this issue :
> 
> * Finalize recommendations lists
> * Update documents for recommendation system

- The current recommendation lists can be used for this version.

- What can I do for the document?

**Comment by sepandhaghighi** [comment]
> > @AlirezaZolanvari
> > I updated `ConfusionMatrix` object and `save_html` method with recommendation system and also added dataset-type section to HTML report.
> > Please take a look at these updates and fix any possible bug that was not found by me.
> > Our last missions in this issue :
> > 
> > * Finalize recommendations lists
> > * Update documents for recommendation system
> 
> * The current recommendation lists can be used for this version.
> * What can I do for the document?

@AlirezaZolanvari 

- First please test `ConfusionMatrix` updates (`cm..imbalance`,`cm.recommended`,`cm.binary`) and `save_html` output with highlight and give me some feedback.
- Write some tests for 3 new functions (`statistic_recommend`,`binary_check` and `imbalance_check`) in `Test/function_test.py`.
- I will add this do document

**Comment by sepandhaghighi** [comment]
@AlirezaZolanvari 

Just a reminder

**Comment by AlirezaZolanvari** [comment]
@sepandhaghighi 
Please check the test functions.
All other functions seems o.k.

**Comment by sepandhaghighi** [comment]
@AlirezaZolanvari 
`Version 1.9` is ready.
I added parameter recommender section to document and `README.md` and also update files and tags for new version
Please take a look at these changes and report any possible bug that was not found by me.
We will release this version on 25 Feb.
