### ISSUE TITLE
Optimize print in high dimension matrix 

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/pycm#120]

**Comment by AlirezaZolanvari** [comment]
High dimensional CMs can be demonstrated through a CSV file.

**Comment by sepandhaghighi** [comment]
Hi @AlirezaZolanvari
Please create a warning message for high dimension matrix print and add to `pycm_param.py` line 25 in branch `dev`.
And also tell me what is your opinion about this warning threshold? (10< classes ? 5< classes ? ...)

Note : Please referenced issues in your commits (`commit -m "message #120"`)

**Comment by sepandhaghighi** [comment]
> High dimensional CMs can be demonstrated through a CSV file.

About this option : 
I think there is no need to additional method and we can save matrix by `save_csv` in a separate file called `filename_matrix.csv`. OK ?

**Comment by AlirezaZolanvari** [comment]
> Hi @AlirezaZolanvari
> Please create a warning message for high dimension matrix print and add to `pycm_param.py` line 25 in branch `dev`.
> And also tell me what is your opinion about this warning threshold? (10< classes ? 5< classes ? ...)
> 
> Note : Please referenced issues in your commits (`commit -m "message #120"`)

Hi @sepandhaghighi 
I just try to find an appropriate threshold for the number of classes and I think up to 10 classes will be demonstrated properly in all types of reports.

**Comment by AlirezaZolanvari** [comment]
> > High dimensional CMs can be demonstrated through a CSV file.
> 
> @AlirezaZolanvari
> About this option :
> I think there is no need to add additional method and we can save matrix by `save_csv` in a separate file called `filename_matrix.csv` OK ?

At the warning message the save_csv method is going to be suggested.

**Comment by sepandhaghighi** [comment]
@AlirezaZolanvari Thanks for your efforts ;-)
I will update `save_csv` in next few days

**Comment by sepandhaghighi** [comment]
@AlirezaZolanvari 

Please test warning for high dimension matrix and `save_csv` method with 2 new arguments : `save_matrix` & `normalize` for saving matrix in CSV file and give me some feedback ;-)

**Comment by AlirezaZolanvari** [comment]
@sepandhaghighi 
All properties look good. The warning is also checked.
Thanks for your effort.
