### ISSUE TITLE
Change error messages

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/pycm#132]
Hi @AlirezaZolanvari 
Take a look at line 18 - 25 of `pycm_param.py` in `dev` branch.
These are pycm error messages, please check and fix them.

Thanks ;-)

**Comment by AlirezaZolanvari** [comment]
Hi,
I think it's almost done. please check it

**Comment by sepandhaghighi** [comment]
@AlirezaZolanvari Thanks for your effort.
What is your opinion about capitalization ?

**Comment by AlirezaZolanvari** [comment]
I think it's unnecessary.

**Comment by sepandhaghighi** [comment]
@AlirezaZolanvari 👍
