### ISSUE TITLE
Support color names in save_html

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/pycm#146]
Support color names in save_html method : 
1. Silver
2. Gray
3. Red
4. Maroon
5. Yellow
6. Olive
7. Lime
8. Green
9. Aqua
10. Teal
11. Blue
12. Navy
13. Fuchsia
14. Purple

And other X11 colors

**Comment by sepandhaghighi** [comment]
@AlirezaZolanvari please update `TABLE_COLOR` dictionary in `pycm_param.py` with X11 color names.
https://en.wikipedia.org/wiki/Web_colors

**Comment by AlirezaZolanvari** [comment]
Hi @sepandhaghighi 
Is there any other work I can do on this issue?

**Comment by sepandhaghighi** [comment]
> Hi @sepandhaghighi
> Is there any other work I can do on this issue?

Hi @AlirezaZolanvari 
Yes, please update `TABLE_COLOR` dictionary with X11 standard table (I only added 14 colors).

Note : color names should be lower case (example : `mediumseagreen`)
