### ISSUE TITLE
Handle examples output

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/pycm#149]
- Create folder for outputs

**Comment by sepandhaghighi** [comment]
@AlirezaZolanvari 

I moved notebook files to different folders in order to prevent overwriting
Take a look at this update and mention any possible bug that was not found by me. (incorrect link and ...)

Link : https://nbviewer.jupyter.org/github/sepandhaghighi/pycm/blob/dev/Document/Document.ipynb

**Comment by sepandhaghighi** [comment]
@AlirezaZolanvari 
Good precision, but there is no problem `SE` description merged with `CI` section, but if you think it would be better to separate this part, we can do it. 
In the last update I moved document and examples output files (`.pycm`,`.csv`,`.html`,`.obj`) to different folders and create open file links for them, please focus on these links.

**Comment by AlirezaZolanvari** [comment]
@sepandhaghighi 
The output files have already been checked. They seems perfect.
I just want to suggest that the `SE` come beside `CI` section title.

**Comment by sepandhaghighi** [comment]
> @sepandhaghighi
> The output files have already been checked. They seems perfect.
> I just want to suggest that the `SE` come beside `CI` section title.

@AlirezaZolanvari 
Ok, we will talk about this here, #164 
Please, take a look at #112

**Comment by sepandhaghighi** [comment]
fixed
