### ISSUE TITLE
Add Optimized Accuracy with Extended Recall-Precision (OAERP)

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/pycm#153]
M. Hossin and M. Sulaiman. A review on evaluation metrics for
data classification evaluations. International Journal of Data Mining
& Knowledge Management Process, 5(2):1, 2015.

IMPROVING ACCURACY METRIC WITH PRECISION AND
RECALL METRICS FOR OPTIMIZING STOCHASTIC
CLASSIFIER

**Comment by adrianog** [comment]
Hi again
Is this implemented?

PS: thanks again for an amazing library

**Comment by sepandhaghighi** [comment]
> Hi again
> Is this implemented?
> 
> PS: thanks again for an amazing library

Hi @adrianog 

Unfortunately not yet!
We couldn't reproduce paper result, and also there are multiple version of `OAREP` and it is a little vague.
