### ISSUE TITLE
Add contributing guidelines

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/pycm#155]
Add more detail about contributing in `CONTRIBUTING.md`

**Comment by sepandhaghighi** [comment]
Hi @AlirezaZolanvari 

Please check `CONTRIBUTING.md` and update it if needed.

Also please take a look at #112 , after these two issue, I think we are good to go for version 1.9

**Comment by AlirezaZolanvari** [comment]
@sepandhaghighi 
It seems ok. I don't have any other idea about it

**Comment by sepandhaghighi** [comment]
fixed
