### ISSUE TITLE
Add "Standard Error" and "Kappa Standard Error" in document

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/pycm#164]

**Comment by sepandhaghighi** [comment]
@AlirezaZolanvari 

I think everything is okay.
Please double check and confirm ;-)

Link : https://nbviewer.jupyter.org/github/sepandhaghighi/pycm/blob/dev/Document/Document.ipynb

**Comment by AlirezaZolanvari** [comment]
> @AlirezaZolanvari
> 
> I think everything is okay.
> Please double check and confirm ;-)
> 
> Link : https://nbviewer.jupyter.org/github/sepandhaghighi/pycm/blob/dev/Document/Document.ipynb

Thanks for your effort. It looks perfect. ;-)

**Comment by sepandhaghighi** [comment]
fixedd
