### ISSUE TITLE
Unification of references formats

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/pycm#173]
@alirezazolanvari 

Please update `README.md` then I will update `Document.ipynb`

Thanks

**Comment by sepandhaghighi** [comment]
fixed

**Comment by sepandhaghighi** [comment]
@MasiJ Hi
We want to unified format of all references.
Please consider the following :
1- Fork PyCM
2- Update `README.md` references section (under `dev` branch in forked repo)
3- Submit a pull request into `dev`

Best Regards
Sepand Haghighi

**Comment by sepandhaghighi** [comment]
@MasiJ Hi
Do you have any plan for this issue ? 
We scheduled to release `version 2.1`  on next monday (April 29, 2019).

Best Regards
Sepand Haghighi

**Comment by MasiJ** [comment]
I will fix it before Monday. I have plan to do it in weekend.

**Comment by sepandhaghighi** [comment]
@MasiJ Thanks 👍 👍

**Comment by MasiJ** [comment]
all done. But I am not sure changes have been made or not! let me know if
there is a problem.

**Comment by MasiJ** [comment]
@sepandhaghighi 
All references are unified.

Best Regards

**Comment by sepandhaghighi** [comment]
fixed

**Comment by sepandhaghighi** [comment]
@alirezazolanvari here ;-)
