### ISSUE TITLE
Adding a warning about the parameter recommender

### ISSUE THREAD

**Issue by alirezazolanvari** [sepandhaghighi/pycm#174]
In the case of recommending parameters, a warning should be raised to inform that the recommender system assumes that the input is the result of classification over the whole data rather than just a part of it.

**Comment by sepandhaghighi** [comment]
@alirezazolanvari 
Please complete `RECOMMEND_WARNING` in `pycm_param.py`, I will add this warning to reports later.

**Comment by sepandhaghighi** [comment]
@alirezazolanvari 
Warning added to `HTML` report, please check

**Comment by sepandhaghighi** [comment]
fixed
