### ISSUE TITLE
Add ADJUSTED GEOMETRIC-MEAN (AGM)

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/pycm#177]
Reference : Batuwita, R. and Palade, V. (2009). A new performance measure for class
imbalance learning. application to bioinformatics problems. In Machine
Learning and Applications, 2009. ICMLA’09. International Conference
on, pages 545–550. IEEE.

**Comment by sepandhaghighi** [comment]
@alirezazolanvari 
AGM is ready!
Please reformat new reference (`46`) in `README.md`.

**Comment by alirezazolanvari** [comment]
I'll do it asp.
