### ISSUE TITLE
Export CM as json/yaml, and include results (add a flag to current pycm.pycm_obj. save_obj ?)

### ISSUE THREAD

**Issue by adrianog** [sepandhaghighi/pycm#210]
#### Description
Export CM as json/yaml, and include results (add a flag to current pycm.pycm_obj. save_obj ?)

I.e. have flags:
save_vectors=True (might want it to be False for large lists)
save_metrics=False

Appreciate "save_vectors=False" would mean that the reloading from the json would not allow the CM to calculate results anymore, only to read precomputed values.

#### PyCM Version
Not currently possible @ 2.2

**Comment by sepandhaghighi** [comment]
@adrianog Hi

Nice comment, we will ad this option in next releases.

**Comment by adrianog** [comment]
Can we recalculate cm.class_stat, cm.overall_stat from the cm.table ?

If yes we should consider adding a flag for that as well.

Basically:
save_vectors=True (might want it to be False for large lists)
save_cm_table=False
save_class_stat=False
save_overall_stat=False

Note:
- if vectors saved/restored->  after restore, it can (re-)calculate everything
- if save_cm_table saved/restored->  after restore, it can (re-)calculate class_stat, overall_stat

Not sure about this last bullet point, i.e. not sure if the cm_table is sufficient to calculate all stats.

**Comment by sepandhaghighi** [comment]
> Can we recalculate cm.class_stat, cm.overall_stat from the cm.table ?
> 
> If yes we should consider adding a flag for that as well.
> 
> Basically:
> save_vectors=True (might want it to be False for large lists)
> save_cm_table=False
> save_class_stat=False
> save_overall_stat=False
> 
> Note:
> 
> * if vectors saved/restored->  after restore, it can (re-)calculate everything
> * if save_cm_table saved/restored->  after restore, it can (re-)calculate class_stat, overall_stat
> 
> Not sure about this last bullet point, i.e. not sure if the cm_table is sufficient to calculate all stats.

Thanks for your comment.
We can recalculate all parameters from `cm.table`, so I decided to add 2 flags (`save_vectors` and `save_metrics`), and I think we don't need more.

**Comment by adrianog** [comment]
Minor thing, perhaps naming should be more consistent - there's both "stats" and "metrics to refer to the same concept. I wasn't too familiar with the code when I suggested "metrics".

**Comment by sepandhaghighi** [comment]
> Minor thing, perhaps naming should be more consistent - there's both "stats" and "metrics to refer to the same concept. I wasn't too familiar with the code when I suggested "metrics".

It wasn't an important issue, but I renamed flags to `save_stat` and `save_vector`, thanks for your comment ;-)
