### ISSUE TITLE
Add PR-AUC

### ISSUE THREAD

**Issue by adrianog** [sepandhaghighi/pycm#216]
#### Description
Add Precision Recall - Area Under the Curve. ref. https://archive.is/hy3nJ

**Comment by sepandhaghighi** [comment]
We will work on this parameter in next releases

**Comment by sepandhaghighi** [comment]
@alirezazolanvari Please reformat references `55` and `56` in `README.md`.

**Comment by sepandhaghighi** [comment]
fixed
