### ISSUE TITLE
Rename AUC to ROC-AUC, AUCI to ROC-AUC-I

### ISSUE THREAD

**Issue by adrianog** [sepandhaghighi/pycm#218]
As per title, since we can have the AUC suffix for different metrics.

**Comment by sepandhaghighi** [comment]
@adrianog 
Good idea.
We will do this, in next releases when we add another `AUC` parameters (like #216)

**Comment by sepandhaghighi** [comment]
I added #216 as `AUPR`, now I think there is no need to rename `AUC` to  `ROC-AUC`.
Most of articles used `AUC`  for  Area Under the ROC Curve.

@alirezazolanvari what is your opinion ?

**Comment by alirezazolanvari** [comment]
@sepandhaghighi I think you are right and AUC is more common and there is no name to rename it.

**Comment by sepandhaghighi** [comment]
> @sepandhaghighi I think you are right. AUC is more common and there is no name to rename it.

So I close this issue
