### ISSUE TITLE
Brier score

### ISSUE THREAD

**Issue by adrianog** [sepandhaghighi/pycm#219]
Needs the predicted probabilities as an input. Not sure what the CM will look like (assume rank==1 for the prediction label?).

**Comment by sepandhaghighi** [comment]
@adrianog 
This library focus is not on these kinds of parameters. But maybe we'll do it in the future ;-)

**Comment by alirezazolanvari** [comment]
@adrianog Thanks for your suggestion. In the core group meeting, we decided to implement this feature in future versions.
