### ISSUE TITLE
Model associated with P-Value

### ISSUE THREAD

**Issue by npfah38** [sepandhaghighi/pycm#225]
Documentation does not identify what model the P-Value provided refers to. 

Could you note or explain?

**Comment by sepandhaghighi** [comment]
@npfah38 Thanks for your comment.
You are right we didn't explain model of P-Value, it is an **one-sided** **binomial test** to see if the `Overall Accuracy` is better than the `NIR`.
We will add this information to Document in next releases.

**Comment by sepandhaghighi** [comment]
@alirezazolanvari Please reformat reference `57` in `README.md`.
Don't forget `56` and `55` ;-)

**Comment by sepandhaghighi** [comment]
fixed
