### ISSUE TITLE
Functions and methods change inputs

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/pycm#226]
#### Description
Functions change inputs
#### Steps/Code to Reproduce
```pycon
>>> matrix1={"Class1": {"Class1": 1, "Class2":0}, "Class2": {"Class1": 2, "Class2": 5}}
>>> matrix2 = {"Class1": {"Class1": 1, "Class2":0}, "Class2": {"Class1": 2, "Class2": 5}}
>>> cm3 = ConfusionMatrix(matrix = matrix1,transpose=True) # Transpose Matrix
>>> matrix1 == matrix2
```
#### Expected Behavior
```pycon
True
```
#### Actual Behavior
```pycon
False
```
#### Operating System
Windows 10
#### Python Version
Python 3.6
#### PyCM Version
PyCM 2.3

**Comment by sepandhaghighi** [comment]
## Very important

@alirezazolanvari 
We deal with a major bug!!
I realized that at least one of the functions (`transpose_func`) has this problem (it's because of shallow and deep copy problem in Python).
Please take a closer look at codes and test cases and give me some feedback.

**Comment by alirezazolanvari** [comment]
@sepandhaghighi 
I had checked all the classes. the problem seems to be solved.
Thanks for your effort.

**Comment by sepandhaghighi** [comment]
> @sepandhaghighi
> I had checked all the classes. the problem seems to be solved.
> Thanks for your effort.

Thanks for reviewing ;-)
