### ISSUE TITLE
Adding CI to measurements

### ISSUE THREAD

**Issue by akshaysc** [sepandhaghighi/pycm#237]
Would it be possible to add optional 95% CI to measures such as TPR, FNR, etc, similar to have it is implemented for accuracy? Several academic journals require these measurements and it may be convenient to do the stats all in one place.

**Comment by sepandhaghighi** [comment]
@akshaysc Hi
Thanks for your comment.
We will add these options in next releases.

**Comment by sepandhaghighi** [comment]
@alirezazolanvari Please reformat references ``59` and `60` in `README.md`.
And also `58` from #238

**Comment by sepandhaghighi** [comment]
> @alirezazolanvari Please reformat references `59` and `60` in `README.md`.
> And also `58` from #238

@alirezazolanvari And also `61`

**Comment by sepandhaghighi** [comment]
> > @alirezazolanvari Please reformat references `59` and `60` in `README.md`.
> > And also `58` from #238
> 
> @alirezazolanvari And also `61`

@alirezazolanvari 
Also `62` and `63`
