### ISSUE TITLE
Classes in string when one of actual or target vector is numpy and the other is not

### ISSUE THREAD

**Issue by pyaf** [sepandhaghighi/pycm#240]
#### Description

Hey, I've found a bug in PyCM.
If one of actual and target vectors is a numpy array and the other is not, the classes tend to be strings. 

#### Steps/Code to Reproduce
```
from pycm import *
y_actu = np.array([2, 0, 2, 2, 0, 1, 1, 2, 2, 0, 1, 2])
y_pred = [0, 0, 2, 1, 0, 2, 1, 0, 2, 0, 2, 2]
cm = ConfusionMatrix(actual_vector=y_actu, predict_vector=y_pred) # Create CM From Data
print(cm.classes)
```
#### Expected Behavior

Output should be `[0, 1, 2]`

#### Actual Behavior

Output is `['0', '1', '2']`

#### Operating System

`Linux Ubuntu 18.04`

#### Python Version

`3.7.2`

#### PyCM Version
`2.3`
Tip: `pycm.__version__` is helpful sometimes, it isn't implemented yet.

**Comment by pyaf** [comment]
@sepandhaghighi This is in response to your mail dated 5 Aug 2019.

**Comment by sepandhaghighi** [comment]
@pyaf Hi
Thanks a lot.
It's a major bug, we will fixed it in next releases ;-)

**Comment by sepandhaghighi** [comment]
@sadrasabouri
Another task for you ;-)
I think, there is something wrong with `vector_filter` function.
https://github.com/sepandhaghighi/pycm/blob/60b4cbc790a37c42c865891c8a925e52455c45e6/pycm/pycm_util.py#L112-L129

My suggestion : 

1. Move first part of `matrix_params_calc`  to `vector_filter` function.
https://github.com/sepandhaghighi/pycm/blob/60b4cbc790a37c42c865891c8a925e52455c45e6/pycm/pycm_util.py#L275-L280


2. Call `vector_filter` inside of `matrix_params_calc`
3. Remove this lines
https://github.com/sepandhaghighi/pycm/blob/60b4cbc790a37c42c865891c8a925e52455c45e6/pycm/pycm_obj.py#L834-L835


Notice 1 : You should check all these parts.
Notice 2 : Add a testcase for this condition to `overall_test.py`
Notice 3 : You should rebase your forked repository

**Comment by sadrasabouri** [comment]
Allright!
I'll do this.

**Comment by sepandhaghighi** [comment]
fixed
