### ISSUE TITLE
Add __version__

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/pycm#241]
#### Description
Add `__version__` attribute
#### Steps/Code to Reproduce
```pycon
>>> pycm.__version__
```
#### Expected Behavior
"2.4"
#### Actual Behavior
```pycon
Traceback (most recent call last):
File "<pyshell#1>", line 1, in <module>
pycm.__version__
AttributeError: module 'pycm' has no attribute '__version__'
```
#### Operating System
Windows 10
#### Python Version
Python 3.6
#### PyCM Version
2.4

**Comment by sepandhaghighi** [comment]
@sadrasabouri Hi
Would you please handle this issue?
It's simple, but consider we have a `VERSION` variable in `pycm_param.py` if you want to replace it (recommended) you should replace it wherever it's used.
And also you should update `version_check.py` in `Otherfiles` folder ;-)

**Comment by sadrasabouri** [comment]
OK
I will do that for you.

**Comment by sepandhaghighi** [comment]
fixed
