### ISSUE TITLE
Update ConfusionMatrix?

### ISSUE THREAD

**Issue by felipefariax** [sepandhaghighi/pycm#255]
This lib is extremely useful! I recomend it to every person that works with supervised learning.

My question is: Is it possible to update a ConfusionMatrix over 'epochs'?

Imagine the situation where my dataset is huge. I need to process the data in several steps/mini-batches.

It would be good to update the original ConfusionMatrix with the new predictions of each specific mini-batches. Also, it would be good to have a flag to wait for the completion of the 'epoch' to calculate the metrics, once it will change over the presented inputs.

**Comment by adrianog** [comment]
Can you not manage this externally, I.e. call the library and save results after each iteration.

**Comment by felipefariax** [comment]
I thought that I could save memory. I can save the results and present them just once, but i think that for PyMC I could just use the memory to store the integers of the confusion matrix.

**Comment by sepandhaghighi** [comment]
@felipefariax 
Thanks for your comment ;-)
Most of PyCM metrics need all the data to be calculated, and as @adrianog mentioned above, I suggest you to manage this externally. (By calling the library after each mini-batch)
