### ISSUE TITLE
Add statistical tests to the Compare feature

### ISSUE THREAD

**Issue by fariasfc** [sepandhaghighi/pycm#261]
What do you think to have some statistical tests like: Wilcoxon, t-student, etc in order to evaluate classifiers between different runs on the same dataset?

**Comment by sepandhaghighi** [comment]
Hi @felipefariax 
Thanks for your comment.
Would you please give us more information about your idea ?

**Comment by felipefariax** [comment]
@sepandhaghighi 

One of the most important things in Machine Learning regarding the comparison between models is to validate with statistical tests. https://en.wikipedia.org/wiki/Statistical_hypothesis_testing

Imagine, for example, that we are trying to compare the performance of the Random Forest Classifier in the Iris dataset with a brand new Classification Algorithm. So we setup two experiments with 30 runs each. After we have done all the simulations, we should analyze if the new model has better performance using statistical tests, for example, the WIlcoxon/Mann-Whytnei, t-student, etc to give us a p-value that we can use to invalidate our null hypothesis based on some significance level.

**Comment by alirezazolanvari** [comment]
Hi @fariasfc.
Thanks for your suggestion. In the contributors' weekly meeting, we investigated your suggestion carefully but at last, we found it out of scope for this package in the current state. This package is focused on post-processing but adding statistical tests needs information from the training procedure.  maybe sometime later we can return and think more about it.
