### ISSUE TITLE
Add ARI (Adjusted Rand Index)

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/pycm#270]
#### Description
Add ARI (Adjusted Rand Index)

### Reference
- Santos, J. M., & Embrechts, M. (2009, September). On the use of the adjusted rand index as a metric for evaluating supervised classification. In International conference on artificial neural networks (pp. 175-184). Springer, Berlin, Heidelberg.

- Rand, W. M. (1971). Objective criteria for the evaluation of clustering methods. Journal of the American Statistical association, 66(336), 846-850.

**Comment by sadrasabouri** [comment]
An Introduction to ARI - Wikipedia
https://en.m.wikipedia.org/wiki/Rand_index
