### ISSUE TITLE
normalized_table_calc inefficiency 

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/pycm#279]
#### Description
Recently I found that `normalized_table_calc` function is **too slow** (more than **30%** of the total execution time!!!) and it seems that the reason is the poor performance of `numpy.around` and built-in `round` function in scalar mode!!

I think, we should define our custom rounder function, something like this :

```python
def custom_rounder(input_number,digit):
    p = float(10**digit)
    return int(input_number * p + 0.5)/p
```

Take a look at this [discussion](https://stackoverflow.com/questions/44920655/python-round-too-slow-faster-way-to-reduce-precision)

**Comment by sepandhaghighi** [comment]
@alirezazolanvari @sadrasabouri 
Please check this issue and give me some feedback

**Comment by sadrasabouri** [comment]
So odd.
As @sepandhaghighi mentioned the reason is
```
round is probably better at handling the rounding of negative numbers (as someone commented, it makes a lot extra calls, so the code is more complex). 
```

Your round function seems work properly.
We do not deal with none positive numbers so this should be a better to rounding the numbers.

**Comment by sepandhaghighi** [comment]
@sadrasabouri 
Do you have time to work on this issue?

**Comment by sadrasabouri** [comment]
> @sadrasabouri
> Do you have time to work on this issue?

It seems good, can you milestone this issue so that i can manage it?

**Comment by sepandhaghighi** [comment]
> It seems good, can you milestone this issue so that i can manage it?

Do not hurry, we have enough time ;-)

It's a straightforward issue and just needs to define a new custom **rounder function**.

**Notice 1** : Changing tests is **not allowed** (new function must return **exactly** the previous values)

**Comment by sepandhaghighi** [comment]
fixed
