### ISSUE TITLE
can't find simple way persist the confusion matrix to a csv with a header

### ISSUE THREAD

**Issue by alexryan** [sepandhaghighi/pycm#282]
#### Description
I need something like this:
```
$cat cm_matrix.csv 
noseatbelt,seatbelt,unoccupied
812,15,0
34,828,0
0,0,873
```
but I cannot find a "simple" way to get the header included in the output.

#### Steps/Code to Reproduce

Here's how I can do it with pandas-ml:
```
import pandas as pd
from pandas_ml import ConfusionMatrix

parser = argparse.ArgumentParser()
parser.add_argument('--input-csv')
parser.add_argument('--output-csv')
args = parser.parse_args()

df = pd.read_csv(args.input_csv, names=['images', 'actuals', 'predictions'])
cm = ConfusionMatrix(df['actuals'],df['predictions'])
df2 = cm.to_dataframe()
confusion_matrix_csv = df2.to_csv(args.output_csv, index=None, header=True) 
```

#### Expected Behavior

I want to see something like this:
```
$cat cm_matrix.csv 
noseatbelt,seatbelt,unoccupied
812,15,0
34,828,0
0,0,873
```
but I cannot find a simple way to add the header

#### Actual Behavior

```
$cat cm_matrix.csv 
812,15,0
34,828,0
0,0,873

```
#### Operating System
macOS Catalina

#### Python Version
3.7

#### PyCM Version (Use : `pycm.__version__`)
```
>>> import pycm
>>> pycm.__version__
'2.5'
>>> 
```

**Comment by sepandhaghighi** [comment]
@alexryan 
Thanks for your comment ;-)
We will add this option in a future release

**Comment by sepandhaghighi** [comment]
@sadrasabouri Would you please handle this issue ?
It seems straightforward ;-)

**Comment by sadrasabouri** [comment]
> @sadrasabouri Would you please handle this issue ?
> It seems straightforward ;-)

Yes it does :+1:
which structure should we use in order to determining class names?

**Comment by sepandhaghighi** [comment]
> Yes it does 👍
> which structure should we use in order to determining class names?

@sadrasabouri 
`save_csv` method and `csv_matrix_print` function should be updated.

**Note :** You can create csv header section easily in first loop of `csv_matrix_print` function

**Comment by sepandhaghighi** [comment]
fixed
