### ISSUE TITLE
Some metrics missing, and extension request

### ISSUE THREAD

**Issue by reshusuri** [sepandhaghighi/pycm#284]
Some metrics like fpr micro, macro etc. 

And please include the extension like ROC-AUC curve for multi clasification

**Comment by sepandhaghighi** [comment]
@reshusuri 
Thanks for your comment 💯 
We will add `FPR Macro/Micro`,`TNR Macro/Micro` and `FNR Macro/Micro` in a future release.
But we don't have any plan for adding ROC curve, because we think it's out of PyCM scope.

**Comment by sepandhaghighi** [comment]
fixed
