### ISSUE TITLE
Single category cannot be executed

### ISSUE THREAD

**Issue by Matt-Wang88** [sepandhaghighi/pycm#310]
#### Description

Single category cannot be executed

#### Steps/Code to Reproduce

```
from pycm import ConfusionMatrix
y_actu = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
y_pred = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
cm = ConfusionMatrix(y_actu, y_pred)
print(cm)
```

#### Expected Behavior

Show that all actual categories match the predicted category.

#### Actual Behavior

```
144 y_actu = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
      145 y_pred = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
----> 146 cm = ConfusionMatrix(y_actu, y_pred)
      147 print(cm)

~\AppData\Roaming\Python\Python36\site-packages\pycm\pycm_obj.py in __init__(self, actual_vector, predict_vector, matrix, digit, threshold, file, sample_weight, transpose)
     93                 self, actual_vector, predict_vector, threshold, sample_weight)
     94      #   if len(matrix_param[0]) < 2:
---> 95      #        raise pycmVectorError(CLASS_NUMBER_ERROR)
     96 
     97         __obj_assign_handler__(self, matrix_param)

pycmVectorError: Number of the classes is lower than 2
```

#### Operating System

Windows 10

#### Python Version

Python 3.6.8

#### PyCM Version (Use : `pycm.__version__`)

2.5

**Comment by sepandhaghighi** [comment]
@Matt-Wang88 Hi
Thanks for opening this issue 🥇 
We must have at least 2 classes to make a confusion matrix, your example only have one, is it valid?
@alirezazolanvari Whats your idea ?

**Comment by Matt-Wang88** [comment]
This is an extreme example, but it can actually happen.
Would it be better if the program could create another ["other](url
![plot1](https://user-images.githubusercontent.com/64952935/81281225-217eca00-908c-11ea-99a2-bca20ed822d8.PNG)
) category" by itself?

**Comment by alirezazolanvari** [comment]
@Matt-Wang88 what's your expectation about metrics like TNR? In this case it is 0/0

**Comment by Matt-Wang88** [comment]
In this case, some statistics (TNR) may not exist.

**Comment by sepandhaghighi** [comment]
> In this case, some statistics (TNR) may not exist.

Thanks for your comments 💯 
We will add this option in a next future release
