### ISSUE TITLE
Documentation on usinging weighted_average

### ISSUE THREAD

**Issue by GeetDsa** [sepandhaghighi/pycm#314]
The documentation lacks the description of using `cm.weighted_average()`. Without the contents in the documentation, the users may not be able to use it.

**Comment by sepandhaghighi** [comment]
> The documentation lacks the description of using `cm.weighted_average()`. Without the contents in the documentation, the users may not be able to use it.

https://www.pycm.ir/doc/index.html#Weighted-average
