### ISSUE TITLE
CM Aggregation

### ISSUE THREAD

**Issue by amiiir** [sepandhaghighi/pycm#326]
#### Description
Because the datasets are usually huge, more often than not we do the training and testing in batches. So we have to calculate the confusion matrix of each batch, and then we should be able to aggregate them integrally.
So I think it's useful to have a method like `update_cm(total_cm, new_cm)` or something like that.

**Comment by sepandhaghighi** [comment]
@amiiir 
Thanks for your comment ;-)
What's your idea about this format ? 
```pycon
>>> new_cm = cm1 + cm2

```

**Comment by amiiir** [comment]
Well it's OK, but since the only valid operation on the CM is summation, I thought operator overloading would be misleading.
But otherwise I'm OK with it

**Comment by adrianog** [comment]
If I might, I think operator overloading is a bad idea. A meaningful method name much better.

**Comment by sepandhaghighi** [comment]
@adrianog 
Thanks for your comment ;-)
Why you think operator overloading is a bad idea?

**Comment by sepandhaghighi** [comment]
@adrianog @amiiir 
What's your idea about this format ?
I think returning new object is better than updating.  
```pycon
>>> cm1 = ConfusionMatrix([1,2,2,1],[1,2,2,2])
>>> cm2 = ConfusionMatrix([2,2,2,1],[2,2,2,2])
>>> cm3 = ConfusionMatrix([1,1,1,2],[1,1,1,2])
>>> cm_combined1 = cm1.combine(cm2)
>>> cm_combined2 = cm1.combine(cm3)
```

**Comment by sepandhaghighi** [comment]
@sadrasabouri @alirezazolanvari  ??

**Comment by amiiir** [comment]
@sepandhaghighi 
Yes, maybe I wasn't clear, but this is exactly what I had in mind:
as a static method:
`total_cm = update_cm(total_cm, batch_cm)`
or as an instance method:
`total_cm = total_cm.combine(batch_cm)`

Either is good, and also I think we can have both too.
This is actually common, for example in `numpy`:
```python
>>> a = np.array([1, 2, 3])

>>> b = np.array([4, 5, 6])

>>> result = np.dot(a, b)
32
>>> result = a.dot(b)
32
```

**Comment by sadrasabouri** [comment]
> Well it's OK, but since the only valid operation on the CM is summation, I thought operator overloading would be misleading.
> But otherwise I'm OK with it

Hi @amiiir
Thanks for your attention.
I actually do agree with `+`.
You're right about it's issues, but see how simple it is in the first look compared to other solutions.
It is actually result of union of separate observations, so `+` operator seems reasonable to me, although any other solution will be appreciated.

**Comment by adrianog** [comment]
@sepandhaghighi I think it does not convey information as well as a fittingly thought-out name - and on the plus side it doesn't add anything apart from syntactic sugar. Are you using overloaded operators for anything else? If not I would keep the project free from them.

That said, looking at the examples again, this case is perhaps completely unambiguous.
i.e. you are pretty sure you're never going to want __add_ to mean anything else in the future.

**Comment by alirezazolanvari** [comment]
Hi all
I prefer to have this option as a method rather than an overloaded operator. It seems more compatible with other parts.

**Comment by sepandhaghighi** [comment]
@sadrasabouri 
Do you have any interest to handle this issue ?

**Comment by sadrasabouri** [comment]
> @sadrasabouri
> Do you have any interest to handle this issue ?

That's all right.
