### ISSUE TITLE
Add array attribute

### ISSUE THREAD

**Issue by alirezazolanvari** [sepandhaghighi/pycm#328]
#### Description
Add `array` attribute which returns the confusion matrix in the form of a `NumPy array`. This can be helpful to apply different operations over the confusion matrix for different purposes such as aggregation, normalization, and combination.

#### Steps/Code to Reproduce
```pycon
>>> from pycm import *
>>> cm = ConfusionMatrix(matrix={1:{1:22,0:1},0:{0:20,1:2}})
>>> array = cm.array
```
#### Expected Behavior
```pycon
>>> cm.array
array([[20,  2],
       [1,  22]])
```
#### Operating System
Windows 10
#### Python Version
Python 3.5.2
#### PyCM Version (Use : `pycm.__version__`)
2.8

**Comment by sepandhaghighi** [comment]
@alirezazolanvari Good point ;-)
It seems straightforward, do you have enough time to implement it ?
Also I think we need to generate `normalized_array`
Take a look at [this topic](https://stackoverflow.com/questions/54021117/convert-dictionary-to-numpy-array) in stackoverflow

**Comment by sepandhaghighi** [comment]
@sadrasabouri 
It seems @alirezazolanvari doesn't have enough free time to complete this issue (after about **2 months**)
If it's possible, please complete his work in `array` branch (add **tests**) and create a PR ;-)

Best Regards
