### ISSUE TITLE
Add plot method

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/pycm#330]
#### Description
Add plot as a new method for `ConfusionMatrix`
```pycon
>>> cm = ConfusionMatrix([1,2,3,2],[1,2,2,2])
>>> cm.plot(normalize=False, title='Confusion matrix')
```

**Comment by sepandhaghighi** [comment]
@sadrasabouri
Do you have any interest to handle this issue ?

**Comment by sadrasabouri** [comment]
> @sadrasabouri
> Do you have any interest to handle this issue ?

Yes that seems really nice 😍 👍
