### ISSUE TITLE
 refactor average method

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/pycm#332]
#### Description
Simplify `average` method by `weighted_average` :
```python
return weighted_average(self, param=param, weight=self.POP, none_omit=none_omit)
```

**Comment by sepandhaghighi** [comment]
@sadrasabouri Please work on this issue after #331 merge

**Comment by sadrasabouri** [comment]
> @sadrasabouri Please work on this issue after #331 merged

OK I'll handle it.
