### ISSUE TITLE
Add metric_off parameter

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/pycm#341]
#### Description
Add `metric_off` parameter to `ConfusionMatrix` object to prevent metrics calculation.

**Comment by sepandhaghighi** [comment]
@sadrasabouri @alirezazolanvari 
What's your idea ?
**Notice :** I'm not sure about the name of this parameter!

**Comment by sadrasabouri** [comment]
Is it be boolean?
I think that's nice, but `metrics_off` seems more reasonable.
