### ISSUE TITLE
ROC-AUC Calculation

### ISSUE THREAD

**Issue by ghnreigns** [sepandhaghighi/pycm#355]
#### Description
I have noticed that for the Area under the ROC curve calculation, the threshold is only fixed to T=0.5? Just want to clarify because the example given does not pass in predicted probabilities - and therefore, one cannot get the overall AUC for all thresholds

**Comment by sepandhaghighi** [comment]
> #### Description
> I have noticed that for the Area under the ROC curve calculation, the threshold is only fixed to T=0.5? Just want to clarify because the example given does not pass in predicted probabilities - and therefore, one cannot get the overall AUC for all thresholds

@ghnreigns Hi
As you can see [here](https://www.pycm.ir/doc/index.html#AUC-(Area-under-the-ROC-curve)), PyCM **estimates** ROC-AUC by a single point of TPR/FPR space.
But you have this option to calculate ROC-AUC with different thresholds, take a look at [this example](https://www.pycm.ir/doc/Example3.html)
Please let me know if you have any questions

**Comment by alirezazolanvari** [comment]
Hi @ghnreigns 
Thanks for your nice suggestion. In the core group meeting, we decided to determine the ROC-AUC more precisely in future versions.
