### ISSUE TITLE
Sensitivity Index Support 

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/pycm#357]
#### Description
Support Sensitivity Index (d-prime)

#### Reference
MacMillan, N.; Creelman, C. (2005). Detection Theory: A User's Guide. Lawrence Erlbaum Associates. ISBN 9781410611147.

[Wikipedia Page](https://en.wikipedia.org/wiki/Sensitivity_index)

**Comment by sepandhaghighi** [comment]
@alirezazolanvari @sadrasabouri 
What's your idea about this method name, `d_prime` or `SI`?

**Comment by sadrasabouri** [comment]
I think it'll be more memorable if it's `d_prime`.
Anyway I'm recommending another one : `sensitivity_index`.

I prefer them in this way:
`SI` < `sensitivity_index` < `d_prime`

**Comment by alirezazolanvari** [comment]
I personally prefer `sensitivity_index`. It's more clear.
