### ISSUE TITLE
make abbreviating of class labels in html output configurable 

### ISSUE THREAD

**Issue by daanvdn** [sepandhaghighi/pycm#364]
in `pycm.pycm_output.html_table` class names whose str representation is longer than 6, the class name is abbreviated to the first 4 characters. It would be good if this behaviour could be configured (turned on / off)

**Comment by sepandhaghighi** [comment]
@daanvdn Good point 👍 

@alirezazolanvari @sadrasabouri Any suggestion for name?

**Comment by sadrasabouri** [comment]
a boolean flag named `long_name` may be good.

**Comment by sepandhaghighi** [comment]
@alirezazolanvari What's your opinion?
