### ISSUE TITLE
图片该如何保存？使用plt.savefig()保存的是一张空白图片

### ISSUE THREAD

**Issue by tanjiu** [sepandhaghighi/pycm#450]
#### Description
使用plt.savefig()保存的是一张空白图片，好像使用plt.show()时会显示两张图片，一张空白的一张是混淆矩阵，但是保存的时候只会保存那张空白的
#### Steps/Code to Reproduce
           cm.plot(cmap=plt.cm.Blues, number_label=True)
            plt.show()
            plt.savefig(fname="C:\\Users\\111\\Desktop\\222\\%s" % '237')

**Comment by sadrasabouri** [comment]
Try this one:
```
cm.plot(cmap=plt.cm.Blues, number_label=True)
plt.savefig(fname="C:\\Users\\111\\Desktop\\222\\%s" % '237')
plt.show()
```

**Comment by tanjiu** [comment]
> Try this one:
> 
> ```
> cm.plot(cmap=plt.cm.Blues, number_label=True)
> plt.savefig(fname="C:\\Users\\111\\Desktop\\222\\%s" % '237')
> plt.show()
> ```

Thanks a lot, problem solved
