### ISSUE TITLE
Modern issue templates

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/pycm#522]
#### Description
Updating repo issue templates

Reference:
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by sadrasabouri** [comment]
[This](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) link is providing complete information for it.
