### ISSUE TITLE
Make pycm available to download with conda

### ISSUE THREAD

**Issue by jsthivierge** [sepandhaghighi/pycm#90]
I want to be able to add pycm as a dependency with conda.

Currently it seems to be available with pip, but I would like to install pycm with the following command:

```
conda install pycm
```

Thanks !

**Comment by sepandhaghighi** [comment]
@jsthivierge Good issue.
I will add this in next version ;-)

**Comment by sepandhaghighi** [comment]
@jsthivierge Hi

Now we are available in anaconda cloud : `conda install -c sepandhaghighi pycm `

Best Regards
