### ISSUE TITLE
Add method to rename classes

### ISSUE THREAD

**Issue by Erotemic** [sepandhaghighi/pycm#98]
It would be useful if there was a method to rename the classes.

In many workflows it is common to encode class names as integers. However, when working with final results it is most useful to convert these integers back into the string class names. 

It would be useful to do this after the construction of the `ConfusionMatrix`, because it is more efficient to remap the labels on the matrix rows and columns than it is to rename each item in the actual and predicted vectors (which can be quite large). 

Something like ConfusionMatrix.rename(mapping) or ConfusionMatrix.relabel(mapping) might be a good method signature where `mapping` is a dictionary of old names to new names. It would also be useful if this method "did the right thing" when multiple old names mapped to a single new name (i.e. sum the counts in the corresponding matrix cells).

**Comment by sepandhaghighi** [comment]
@Erotemic 

Good point ;-) 
I will add this in next releases ;-)
