### ISSUE TITLE
Names of matrix and normalized_matrix methods are confusing. 

### ISSUE THREAD

**Issue by Erotemic** [sepandhaghighi/pycm#99]
I would have expected matrix and normalized matrix to return the confusion matrix as a numpy array or a pandas DataFrame. However instead it prints a string representation. 

It might be a more clear design if these functions were renamed to print_matrix / print_normalized_matrix and matrix / normalized_matrix were added to return a value that the a user can work with.

**Comment by sepandhaghighi** [comment]
@Erotemic 
yeah, I know names are a little vague :-)
I will solve this in next releases
Thanks ;-)
